### ISSUE TITLE
Implement EventSubscriberInterface Function

### ISSUE THREAD

**Issue by clicktrend** [ddeboer/GuzzleBundle#5]
Error occurs at

GuzzleBundle / Guzzle / Http / Plugin / DataCollectorPlugin.php

which implements

Symfony\Component\EventDispatcher\EventSubscriberInterface

but static function getSubscribedEvents is not implemented.

**Comment by gimler** [comment]
my PR https://github.com/ddeboer/GuzzleBundle/pull/7 fix this. vote for it ;)

**Comment by clicktrend** [comment]
+1
