### ISSUE TITLE
Fatal error: Class 'Guzzle\Service\ServiceBuilder'  after vendors update

### ISSUE THREAD

**Issue by arturmartins** [ddeboer/GuzzleBundle#6]
After I did a vendors update, I can't get deps.lock file created due this error:

Fatal error: Class 'Guzzle\Service\ServiceBuilder' not found in /var/www/Symfony/vendor/bundles/Ddeboer/GuzzleBundle/Guzzle/Service/ServiceBuilder.php on line 16

from vendor/bundles/Ddeboer/GuzzleBundle/Guzzle/Service/ServiceBuilder.php:

```
 1  <?php
 2  
 3  namespace Ddeboer\GuzzleBundle\Guzzle\Service;
 4  
 5  use Guzzle\Service\Exception\ClientNotFoundException;
 6  
 7  use Guzzle\Service\ServiceBuilder as BaseServiceBuilder;
 8  
 9  /**
10   * Service builder to generate service builders and service clients from
11   * configuration settings
12   *
13   * @author Gordon Franke <info@nevalon.de>
14   */
15  class ServiceBuilder extends BaseServiceBuilder
16  {
```

[...]

It was working before. Any ideas how to solve it?

**Comment by arturmartins** [comment]
Guzzle v2.6.0 refactored their ServiceBuilder into a more complex solution https://github.com/guzzle/guzzle/tree/v2.6.0/src/Guzzle/Service/Builder

use 2.5.0 version will not brake it.

on deps file, append the version to guzzle to avoid this problem in the future:

 [Guzzle]
     git=git://github.com/guzzle/guzzle.git
     target=/guzzle
     version=v2.5.0

**Comment by gimler** [comment]
see my PR https://github.com/ddeboer/GuzzleBundle/pull/7 it works with the guzzle trunk. vote for it ;)
