### ISSUE TITLE
We can help give us access to the Repro

### ISSUE THREAD

**Issue by gimler** [ddeboer/GuzzleBundle#8]
Hello @ddeboer,

i think you have enough todo with other things. So can you give us me and mtdowling the author of guzzle the permission to manage this repro to so we can help you.

We use the bundle in our daily business.

What do you think?

**Comment by predakanga** [comment]
+1 - the bundle has a lot of potential, I'd love to see it maintained for the long term.

**Comment by ddeboer** [comment]
Sorry for the lack of maintenance. I'm rather short on time now and not using Guzzle in any current projects, which makes maintaining this bundle harder. 

@gimler, I've made both you and Michael collaborators on this repository. Feel free to add your (and others') names to the `composer.json` or the license. When I have some more time to play with Guzzle again, I hope to also give this bundle the attention it deserves.

**Comment by gimler** [comment]
i will add a MIT LICENSE File and a composer.json
